spring.application.name=Omni_Bridge

# App Config
app.base.url=
app.frontend.url=
spring.profiles.active=dev
server.port=${PORT:8080}

# JWT Config
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration-ms=1296000000

# OTP Config
otp.expiration-ms=300000
otp.cleanup-rate-ms=60000
otp.length=6
ott.token.expiry.seconds=300
ott.cleanup-rate-ms=300000

# Mail Configuration
spring.mail.from=${MAIL_USERNAME}
brevo.api.key=${BREVO_API_KEY}

# Rate Limiting Config
rate-limit.duration=1
rate-limit.login=5
rate-limit.register=3
rate-limit.otp=5
rate-limit.ott=5

# Logging Config
spring.output.ansi.enabled=always
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level){yellow} %clr([%15.15t]){cyan} %clr(%-40.40logger{39}){blue} : %m%n