spring.application.name=Omni_Bridge

spring.datasource.url=jdbc:postgresql://localhost:5432/omni_bridge
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration